// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::driveTrainTopLeft;
std::shared_ptr<SpeedController> RobotMap::driveTrainTopRight;
std::shared_ptr<SpeedController> RobotMap::driveTrainBottomLeft;
std::shared_ptr<SpeedController> RobotMap::driveTrainBottomRight;
std::shared_ptr<SpeedController> RobotMap::driveTrainCenter;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveTrainTopLeft.reset(new TalonSRX(0));
    lw->AddActuator("DriveTrain", "TopLeft", std::static_pointer_cast<TalonSRX>(driveTrainTopLeft));

    driveTrainTopRight.reset(new TalonSRX(1));
    lw->AddActuator("DriveTrain", "TopRight", std::static_pointer_cast<TalonSRX>(driveTrainTopRight));
    
    driveTrainBottomLeft.reset(new TalonSRX(2));
    lw->AddActuator("DriveTrain", "BottomLeft", std::static_pointer_cast<TalonSRX>(driveTrainBottomLeft));
    
    driveTrainBottomRight.reset(new TalonSRX(3));
    lw->AddActuator("DriveTrain", "BottomRight", std::static_pointer_cast<TalonSRX>(driveTrainBottomRight));
    
    driveTrainCenter.reset(new TalonSRX(4));
    lw->AddActuator("DriveTrain", "Center", std::static_pointer_cast<TalonSRX>(driveTrainCenter));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
