// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveTeleop.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveTeleop::DriveTeleop(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_X = 0.0;
	m_Y = 0.0;
	m_Z = 0.0;
	m_scalar = 0.0;
	joystick = Robot::oi->getJoystick1();
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DriveTeleop::Initialize() {
	Robot::driveTrain->StopMoving();
}

// Called repeatedly when this Command is scheduled to run
void DriveTeleop::Execute() {

	m_scalar = -0.5 * joystick->GetRawAxis(3) + 0.5;
	m_X = joystick->GetRawAxis(0);
	m_Y = joystick->GetRawAxis(1);
	m_Z = joystick->GetRawAxis(2);

	//Each if statement is to make sure the speed value stays between -1.0 and 1.0.

	if (Robot::driveTrain->GetDirection() == static_cast<int>(Direction::FORWARD))
	{
		Robot::driveTrain->SetMotorSpeed(DriveMotor::TOP_LEFT, m_scalar * ((m_Y - m_Z >= 1.0) ? 1.0 : ((m_Y - m_Z <= -1.0) ? -1.0 : m_Y - m_Z)));
		Robot::driveTrain->SetMotorSpeed(DriveMotor::TOP_RIGHT, m_scalar * -((m_Y + m_Z >= 1.0) ? 1.0 : ((m_Y + m_Z <= -1.0) ? -1.0 : m_Y + m_Z)));
		Robot::driveTrain->SetMotorSpeed(DriveMotor::BOTTOM_LEFT, m_scalar * ((m_Y - m_Z >= 1.0) ? 1.0 : ((m_Y - m_Z <= -1.0) ? -1.0 : m_Y - m_Z)));
		Robot::driveTrain->SetMotorSpeed(DriveMotor::BOTTOM_RIGHT, m_scalar * -((m_Y + m_Z >= 1.0) ? 1.0 : ((m_Y + m_Z <= -1.0) ? -1.0 : m_Y + m_Z)));
		Robot::driveTrain->SetMotorSpeed(DriveMotor::CENTER, m_scalar * -((m_X >= 1.0) ? 1.0 : ((m_X <= -1.0) ? -1.0 : m_X)));

	}
	else
	{
		Robot::driveTrain->SetMotorSpeed(DriveMotor::TOP_RIGHT, m_scalar * ((m_Y - m_Z >= 1.0) ? 1.0 : ((m_Y - m_Z <= -1.0) ? -1.0 : m_Y - m_Z)));
		Robot::driveTrain->SetMotorSpeed(DriveMotor::TOP_LEFT, m_scalar * -((m_Y + m_Z >= 1.0) ? 1.0 : ((m_Y + m_Z <= -1.0) ? -1.0 : m_Y + m_Z)));
		Robot::driveTrain->SetMotorSpeed(DriveMotor::BOTTOM_RIGHT, m_scalar * ((m_Y - m_Z >= 1.0) ? 1.0 : ((m_Y - m_Z <= -1.0) ? -1.0 : m_Y - m_Z)));
		Robot::driveTrain->SetMotorSpeed(DriveMotor::BOTTOM_LEFT, m_scalar * -((m_Y + m_Z >= 1.0) ? 1.0 : ((m_Y + m_Z <= -1.0) ? -1.0 : m_Y + m_Z)));
		Robot::driveTrain->SetMotorSpeed(DriveMotor::CENTER, m_scalar * ((m_X >= 1.0) ? 1.0 : ((m_X <= -1.0) ? -1.0 : m_X)));

	}
}

// Make this return true when this Command no longer needs to run execute()
bool DriveTeleop::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void DriveTeleop::End() {
	Robot::driveTrain->StopMoving();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveTeleop::Interrupted() {
	Robot::driveTrain->StopMoving();
}
